// ── Script Generation ─────────────────────────────────────
function detectOS() {
  const platform  = navigator.platform.toLowerCase();
  const userAgent = navigator.userAgent.toLowerCase();
  if (platform.indexOf('win') !== -1) return 'windows';
  if (platform.indexOf('mac') !== -1 || userAgent.indexOf('mac') !== -1) return 'mac';
  return 'linux';
}

function getVideoBaseName() {
  return videoFilename.replace(/\.[^/.]+$/, '');
}

function sanitizeFilename(filename) {
  return filename
    .replace(/[^\x00-\x7F]/g, '_')
    .replace(/[<>:"|?*]/g, '_')
    .replace(/\s+/g, '_')
    .replace(/_+/g, '_');
}

function generateExtractScript() {
  const selected = chaptersArr.filter((_, i) => chapterSelections[i]);
  if (selected.length === 0) { showErrorDialog('Nothing Selected', 'Select one or more chapters first.'); return; }
  if (!videoFilename)        { showErrorDialog('No Video',          'No video file loaded.');              return; }

  const os               = detectOS();
  const baseName         = sanitizeFilename(getVideoBaseName());
  const safeVideoFilename = sanitizeFilename(videoFilename);
  let script = '';

  if (os === 'windows') {
    script += '@echo off\n';
    script += `REM Extract selected chapters from ${videoFilename}\n`;
    script += `REM Generated by Tilester Review\n\n`;
    selected.forEach((ch) => {
      const chapterIndex = chaptersArr.indexOf(ch);
      const outputName   = `${baseName}_chapter${String(chapterIndex + 1).padStart(3, '0')}.mp4`;
      script += `echo Extracting ${ch.title}...\n`;
      script += `ffmpeg -i "${safeVideoFilename}" -ss ${ch.start_time.toFixed(3)} -to ${ch.end_time.toFixed(3)} -c copy "${outputName}"\n\n`;
    });
    script += 'echo Done!\n';
  } else {
    script += '#!/bin/bash\n';
    script += `# Extract selected chapters from ${videoFilename}\n`;
    script += `# Generated by Tilester Review\n\n`;
    selected.forEach((ch) => {
      const chapterIndex = chaptersArr.indexOf(ch);
      const outputName   = `${baseName}_chapter${String(chapterIndex + 1).padStart(3, '0')}.mp4`;
      script += `echo "Extracting ${ch.title}..."\n`;
      script += `ffmpeg -i "${safeVideoFilename}" -ss ${ch.start_time.toFixed(3)} -to ${ch.end_time.toFixed(3)} -c copy "${outputName}"\n\n`;
    });
    script += 'echo "Done!"\n';
  }

  downloadScript(script, os === 'windows' ? 'cmd' : 'sh', 'extract');
}

function generateExtractMergeScript() {
  const selected = chaptersArr.filter((_, i) => chapterSelections[i]);
  if (selected.length === 0) { showErrorDialog('Nothing Selected', 'Select one or more chapters first.'); return; }
  if (!videoFilename)        { showErrorDialog('No Video',          'No video file loaded.');              return; }

  const os               = detectOS();
  const baseName         = sanitizeFilename(getVideoBaseName());
  const safeVideoFilename = sanitizeFilename(videoFilename);
  const mergedOutput     = `${baseName}_cut_merged.mp4`;
  let script = '';

  if (os === 'windows') {
    script += '@echo off\n';
    script += `REM Extract and merge selected chapters from ${videoFilename}\n`;
    script += `REM Generated by Tilester Review\n\n`;
    selected.forEach((ch, idx) => {
      const tempName = `temp_segment_${idx}.mp4`;
      script += `echo Extracting segment ${idx + 1}/${selected.length}...\n`;
      script += `ffmpeg -i "${safeVideoFilename}" -ss ${ch.start_time.toFixed(3)} -to ${ch.end_time.toFixed(3)} -c copy "${tempName}"\n`;
    });
    script += '\necho Creating concat list...\n';
    script += `(for %%i in (temp_segment_*.mp4) do @echo file '%%i') > concat_list.txt\n\n`;
    script += 'echo Merging segments...\n';
    script += `ffmpeg -f concat -safe 0 -i concat_list.txt -c copy "${mergedOutput}"\n\n`;
    script += 'echo Cleaning up temporary files...\n';
    script += 'del temp_segment_*.mp4\ndel concat_list.txt\n\necho Done!\n';
  } else {
    script += '#!/bin/bash\n';
    script += `# Extract and merge selected chapters from ${videoFilename}\n`;
    script += `# Generated by Tilester Review\n\n`;
    selected.forEach((ch, idx) => {
      const tempName = `temp_segment_${idx}.mp4`;
      script += `echo "Extracting segment ${idx + 1}/${selected.length}..."\n`;
      script += `ffmpeg -i "${safeVideoFilename}" -ss ${ch.start_time.toFixed(3)} -to ${ch.end_time.toFixed(3)} -c copy "${tempName}"\n`;
    });
    script += '\necho "Creating concat list..."\n';
    script += 'for f in temp_segment_*.mp4; do echo "file \'$f\'"; done > concat_list.txt\n\n';
    script += 'echo "Merging segments..."\n';
    script += `ffmpeg -f concat -safe 0 -i concat_list.txt -c copy "${mergedOutput}"\n\n`;
    script += 'echo "Cleaning up temporary files..."\nrm temp_segment_*.mp4\nrm concat_list.txt\n\necho "Done!"\n';
  }

  downloadScript(script, os === 'windows' ? 'cmd' : 'sh', 'extract_merge');
}

function downloadScript(content, extension, scriptType) {
  const baseName = sanitizeFilename(getVideoBaseName());
  const filename = `${baseName}_${scriptType}.${extension}`;
  const blob     = new Blob([content], { type: 'text/plain' });
  const url      = URL.createObjectURL(blob);
  const a        = document.createElement('a');
  a.href         = url;
  a.download     = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
